INSERT INTO Exercise(exercise_name, suggested_weight, exercise_reps, exercise_sets, expected_time, body_target_id, description)
VALUES('Arms High Partial Sit Up', 0, 12, 3, 5, 7, 'Lie on your back, knees bent at 90 degrees, and raise your arms straight overhead, keeping them pointing up throughout the exercise. Sit up halfway, then steadily return to the floor. That’s one rep.'),
       ('Forearm Plank', 0, 1, 3, 5, 7, 'Place your forearms on the floor, elbows directly underneath your shoulders, hands facing forward so that your arms are parallel. Extend your legs behind you, feet hip-width apart. Tuck your tailbone and engage your core, butt, and quads. Hold here for a set amount of time.'),
       ('Side Plank', 0, 1, 3, 6, 7, 'Lie on your right side with your right hand directly underneath your right shoulder. Extend your legs and stack your left foot on top of your right, and squeeze your abs and glutes to lift your hips off the floor. Extend your left hand straight up towards the ceiling and hold for a set amount of time. This is one rep. Be sure to alternate between left and right sides.'),
       ('Leg Lift', 0, 12, 3, 6, 7, 'Lie faceup with your legs extended and your arms on the floor by your sides. If your lower back needs some extra support, you can place your hands right underneath your butt on each side. This is the starting position. Slowly lift your legs up and toward your face, keeping them together and stopping when they are about vertical. Then, slowly lower them back down to the ground. Be sure to keep your back flat on the floor. If you are having trouble with that or feel tension in your lower back, do not lower your legs as far down.')
       
       
       
       
       //Data for 4/8/21
INSERT INTO Exercise(exercise_name, suggested_weight, exercise_reps, exercise_sets, expected_time, body_target_id, description)
VALUES('Grounded Russian Twist', 0 30, 3, 6, 7, 'Sit on the floor with your knees bent and heels resting on the ground. Lean back so that your torso is at 45°. Keep your chest up to stop you from hunching your back. Interlock your fingers and extend your arms in front of you. Turn your torso to the left or right, bringing your hands to touch the ground on that side. Rotate back to centre and then carry on to touch the opposite side. Once you’ve mastered the movement, make it more difficult by raising your heels off the floor and/or holding a weight.'),
      ('Dumbbell Woodchop', 15, 12, 3, 6, 7, 'Stand holding a dumbbell in both hands. Squat down and move the dumbbell over to the outside of your left thigh. Stand up and raise the dumbbell with straight arms, twisting to take it across your torso to finish above your right shoulder. In the final position you should have twisted your entire torso to face the dumbbell and be up on your toes, using your core to hold the position. Twist back to return the dumbbell to the starting position. Do all the required reps on one side and then swap.'),
      ('Medicine Ball Crunch', 13, 15, 3, 7, 7, 'Lie on your back with your knees bent and feet flat on the floor. Hold a medicine ball – 6kg to 10kg should be fine – to your chest. Raise your torso off the floor and press the medicine ball above your head with straight arms. To encourage good form, bring your head forwards between your arms and keep your chest up as your torso reaches vertical. Slowly lower under control, keeping your arms extended so the medicine ball touches the floor behind your head. Keep the movement smooth and controlled.'),
      ('Flutter Kicks', 0, 1, 3, 6, 7, 'Sometimes known as scissor kicks, this movement will certainly feel like it’s carving out your abs. Lie on your back and raise your legs so that they’re roughly 15cm above the ground. Keeping your legs straight throughout, move your legs up and down in a kicking motion, with the movement coming from your hips. Go at a pace that’s comfortable and allows you to keep your legs off the ground for the duration, and make smooth and controlled movements. Work for between 30 and 60 seconds at a time.');     
        