 
INSERT INTO exercise(exercise_name, suggested_weight, exercise_reps, exercise_sets, expected_time, body_target_id, description)
VALUES ('Hammer Curl', 25, 12, 3, 10, 4 ,'Stand holding a pair of dumbbells at arms length by your sides with your palms facing each other. Keeping your elbows tucked, your upper arms locked in place (only your hands and forearms should move), and your palms facing inward, curl the dumbbells as close to your shoulders as you can.Pause, and then slowly lower the weights back to the starting position.'),
        ( 'Dumbbell Skull Crushers', 25, 10, 3, 10, 4, 'Lie down on a bench or the floor holding a pair of dumbbells directly above your chest with your palms facing each other. Your feet should be flat on the floor. Without moving your upper arms, bend your elbows and slowly lower the weights toward the sides of your head. Avoid flaring your elbows. Reverse the move to return to the starting position.'),
        ('Dumbbell Bicep Curl', 30, 12, 3, 10, 4, 'Begin standing tall with your feet about hip-width apart. Keep your abdominal muscles engaged. Hold one dumbbell in each hand. Let your arms relax down at the sides of your body with palms facing forward. Keeping your upper arms stable and shoulders relaxed, bend at the elbow and lift the weights so that the dumbbells approach your shoulders. Your elbows should stay tucked in close to your ribs. Exhale while lifting. Lower the weights to the starting position.'),
        ('Tricep Pushdown', 80, 12, 4, 10, 4, 'Set the cable machine up with the bar at head height. Grab the bar and stand upright with your back straight and your elbows tucked in to your sides. Stand with your feet hip-width apart. Pull the cable down until the bar touches your thighs and pause to squeeze your triceps at the bottom of the move. Then slowly raise the bar back to the starting position. Make sure you don’t lean forwards to aid the press and don’t let your elbows leave your sides, otherwise you’ll lose some of the focus on the triceps.'),
        ('Reverse Dumbbell Bicep Curl', 15, 10, 3, 10, 4, 'Stand holding a dumbbell in each hand using an overhand grip. Your arms should be fully extended and your feet shoulder width apart. Keeping your upper arms stationary and your back straight, curl the weights up towards your shoulders. Continue curling the dumbbells up until they are at shoulder level and your biceps are fully contracted. Hold for a count of one as you squeeze your biceps. Return to the starting position in a smooth arc.'),
        
        ('Chin Ups', 0, 10, 3, 8, 4 ,'Starting Position: Stand under the chin-up bar and reach your arms overhead with your palms facing you.  Reach, jump or lift your body off the floor to grasp the handles firmly with a full grip position (thumbs wrapped around the handles).  Gently cross one leg over the other to stabilize your lower extremity and then stiffen ("brace") your abdominal muscles to stabilize your spine. Depress and retract your scapulae (pull shoulders back and down) and attempt to hold this position throughout the exercise. Slowly exhale and slowly pull your body upwards by flexing (bending) your elbows and pulling your arms down to your sides  Attempt to pull in a motion that drives your elbows directly down towards the floor, keeping your elbows in front of your body. Attempt to keep your body aligned vertically to the floor and avoid swinging your body during your upward pull. Continue pulling upward until your chin is level with the bar or your hands.  Pause momentarily then slowly return to your starting position by allowing your arms to extend back overhead until your arms are fully extended. Repeat the movement'),
        ('Wrist Curl - Extension', 15, 15, 3, 7, 4, 'Holding two dumbbells, kneel and rest your elbows on a bench with approximately a 90 degree bend at the elbows and the dumbbells hanging freely off the edge of the pad. Pronate your forearms (rotate forearms to face palms downward and the bottom of the forearms are resting on the bench) while keeping your wrists in a neutral position (not in flexion or extension). Inhale and slowly allow the wrists to move into flexion (allow dumbbells to move towards the floor) without releasing your grip, extending your arms or leaning forward / backward. Hold this end position briefly. Upward Phase: Exhale and slowly contract your forearm extensor muscles (along the top of the forearm) and roll your wrists to pull the weight up and return the dumbbells back to the starting position.'),
        ('Wrist Curl - Flexion', 10, 15, 3, 7, 4, 'Holding two dumbbells, kneel and rest your elbows on a bench with approximately a 90 degree bend at the elbows and the dumbbells hanging freely off the edge of the pad. Supinate your forearms (rotate the forearms so that the tops are along the bench and the palms are facing upward) keep your wrists in a neutral position. Inhale and slowly allow the wrists to move into extension (allow dumbbells to move towards the floor) without releasing your grip, extending your arms or leaning forward / backward. Hold this end position briefly. Exhale and slowly contract your forearm flexor muscles (along the top of the forearm) rolling your wrists towards you in order to return the dumbbells back to the starting position.'),
        ('Tricep Dips', 0, 12, 3, 10, 4, 'Hoist yourself up on parallel bars with your torso perpendicular to the floor, you will maintain this posture throughout the exercise. (Leaning forward will shift emphasis to your chest and shoulders.) Bend your knees and cross your ankles. Slowly lower your body until your shoulder joints are below your elbows. Push back up until your elbows are nearly straight but not locked.'),
        ('Isolated Tricep Extension', 20, 10, 3, 10, 4, 'Sit on a bench and grab one dumbbell. Form a diamond shape with both hands to grip the top end of the weight. Raise the dumbbell over your head, keeping your elbows up and your core tight. Lower the dumbbell down the top of your back by bending at the elbow, maintaining your strong chest and keeping your shoulders still. Raise the weight by fully extending your arms, pausing for a count to squeeze at the top of the movement.');


  INSERT INTO trainers_exercises(exercise_id, trainer_id)
  VALUES(23,3), (30, 3), (25, 3), (24,3), (22,3), (32, 3), (33, 3), (39, 3), (45, 3), (47, 3), (38, 3), (40, 3), (34, 3), (49, 3), (50,3), (26,3), (31,3), (36, 3), (37, 3);