INSERT INTO exercise(exercise_name, suggested_weight, exercise_reps, exercise_sets, expected_time, body_target_id, description)
        VALUES('Bent-over Row', 45, 10, 3, 12, 2, 'Grip a barbell with palms down so that the wrists, elbows, and shoulders are in a straight line. Lift the bar from the rack, bend forward at the hips, and keep the back straight with a slight bend in the knees. Lower the bar towards the floor until the elbows are completely straight, and keep the back flat as the bar is pulled towards the belly button. Then slowly lower the bar to the starting position and repeat'),
        ('Standing Shrugs', 135, 10, 3, 12, 2, 'Hold a barbell with a palms-down grip with the hands about shoulder-width apart. Keep the knees slightly bent, the hips straight, and the back tall, and raise the shoulders directly upwards to the ears as high as possible, lowering slowly to the original starting position. (Tip: grip the bar and think about pulling the hands apart from one another and focus on only raising/lowering the shoulders - DO NOT roll the shoulders.)'),
        ('Incline Reverse Flys', 40, 10, 3, 12, 2, 'Holding two dumbbells, sit on a bench facing the backrest angled at 45 to 60 degrees. Hold your torso against the backrest and keep your feet firmly placed on the floor. Allow your arms to hang towards the floor with your elbows slightly flexed and palms facing each other. Stiffen your core and abdominal muscles (“bracing”) to stabilize your spine.
           Upward Phase: Exhale and slowly raise the dumbbells up and out to the sides, raising the upper arms, elbows and dumbbells in unison until the arms are near level with the shoulders. Squeeze your scapulae (shoulder blades) together as you reach the end position. In the raised position, the dumbbells should be aligned with, or slightly in front of your ears. Avoid arching your back during the upward phase by keeping your torso firmly pressed into the backrest.
                '),
         ('Single Arm Row', 40, 10, 3, 12, 2, 'Holding a dumbbell in your right hand, bend over to place your left knee and left hand on a bench to support your body weight. Your hand should be placed directly under your shoulder and your knees should be positioned directly under your hips. Gently contract your abdominal / core muscles ("bracing") to stiffen your torso and stabilize your spine. Your back should be flat and head aligned with your spine. Depress and retract your scapulae (pull your shoulders down and back) without arching your low back and maintain this shoulder position throughout the exercise. Extend your right arm (holding the dumbbell) towards the floor without allowing your torso to rotate or shoulder to move towards the floor.
            Upward Movement: Exhale and slowly pull the dumbbell upwards, bending your elbow and pulling your upper arm backwards. Keep your arm close to the side of your body and continue pulling the dumbbell upwards until you are unable to lift any further without rotating your torso. Avoid rotating your body or changing the position of your spine throughout the lift.
                '),
         ('Deadlift (Barbell)', 135, 10, 3, 12, 2, 'Holding a barbell with both hands so that it rests on the front of the thighs, keep a slight bend in both knees and a straight back. Push the hips back while lowering the weight towards the floor until feeling some tension along the back of the legs. To return to standing, push the heels into the floor and pull the knees backwards, keeping the bar very close to the body while standing.
                '),
         ('Lat Pull-down', 100, 10, 3, 12, 2, 'While sitting with your upper thighs restrained under a thigh pad, you pull a hanging bar down toward you, to reach chin level, and then release it slowly back up with control for one repetition. Continue until set it complete'),
         ('Romainain Deadlifts (Dumbell)', 100, 10, 3, 12, 2, 'Grasp two dumbbells and hold them with feet set hip-width apart. Keeping your lower back in its natural arch, bend hips back, your torso forward, and lower yourself until you feel a stretch in your hamstrings. You may bend at the knees. Squeeze your glutes at the top of the movement after coming back up.'),
         ('Inverted Row', 0, 10, 3, 12, 2, 'Set a barbell in a power rack (or use a Smith machine) at about hip height. (About four rungs up should work). Lie underneath it and grab it with hands about shoulder-width apart with the bottom of your heels on floor. Hang from the bar so your body forms a straight line. Squeeze your shoulder blades together and pull yourself up until your back is fully contracted.'),
         ('Burpee', 0, 10, 3, 12, 2, 'Stand with feet outside shoulder-width apart. Next, bend down into a squat position and place your hands on the floor. Now quickly thrust your legs behind, you so you end up at the top of a pushup position. Bring your legs back up so they land outside your hands, and then jump up quickly. That’s one rep.'),
         ('Bentover Reverse Flys', 25, 10, 3, 12, 2, 'Set up as you did for the neutral-grip row, but with lighter dumbbells. Set a timer for three minutes. Raise your arms out to your sides 90 degrees, squeezing your shoulder blades together at the top for a second. Complete your set and then rest until the end of three minutes, when your timer goes off.'),
         ('Back Extensions', 45, 10, 3, 12, 2, 'Lock your legs into a back extension bench and allow your torso to bend forward so that your hips are bent almost 90 degrees. Extend your hips so that your body forms a straight line.'),
         ('Superman', 0, 10, 3, 12, 2, 'Raise your hands and legs off the floor (and hold them straight) so that only your hips remain in contact with it. Contract your back as if you were trying to touch your heels and elbows to the ceiling.');
         
                  INSERT INTO trainers_exercises(exercise_id, trainer_id)
                  VALUES(1,4), (8,4), (12,4), (10,4), (6,4), (13,4), (18,4), (6,4), (22,4), (2,4), (24,4), (30,4), (11,4), (32,4), (29,4), (25,4), (43,4), (46,4), (38,4), (40,4), (23,4), (4,4);     