 ('Squat Jump', 0, 3, 8, 8, 1, 'With your feet hip-width apart, squat until your thighs are parallel to the floor, and then jump as high as you can. Allow your knees to bend 45 degrees when you land, pause in deep squat position for one full second, and then jump again.')
 ('Walking Single-leg Straight-leg Deadlift Reach', 0, 3, 8, 10, 1, 'Stand with your feet hip-width apart and your arms hanging to the side of your thighs. Lift your right leg behind you. Keeping your lower back naturally arched, bend forward at your hips and lower your torso until it’s nearly parallel to the floor while you reach your opposite hand to the floor. Return to the starting position, take two steps forward, then repeat the movement with the opposite leg.'),
 ('Side Lunge', 0, 3, 12, 8, 1, 'Stand with your feet hip-width apart and your arms hanging to the side of your thighs. Lift your right leg behind you. Keeping your lower back naturally arched, bend forward at your hips and lower your torso until it’s nearly parallel to the floor while you reach your opposite hand to the floor. Return to the starting position, take two steps forward, then repeat the movement with the opposite leg.'),
 ('Single-Leg Hip Raise', 5, 3, 12, 5, 1, 'Stand with your feet hip-width apart and your arms hanging to the side of your thighs. Lift your right leg behind you. Keeping your lower back naturally arched, bend forward at your hips and lower your torso until it’s nearly parallel to the floor while you reach your opposite hand to the floor. Return to the starting position, take two steps forward, then repeat the movement with the opposite leg.'),
 ('Alternating Drop Lunge', 0, 3, 10, 5, 1, 'Stand with your feet hip-width apart, hands on hips. Keep your chest and eyes up, shoulders squared. Cross your right leg behind your left, and bend both knees, lowering your body until your left thigh is nearly parallel to the floor. Return to start and repeat, switching sides.'),
 ('Box Squat Jumps', 0, 1, 10, 10, 1, 'Perform 10 box squat jumps every minute on the minute for 10 minutes. That means that you should set a time for 10 minutes, then do 1o reps every time a new minute starts. Rest during the remainder time for each period.'),
 ('Deadlift', 60, 5, 8, 10, 1, 'Stand tall with the barbell in front of you, then squat down and grasp it with an overhand grip. Keeping your chest up and core braced, press down through your heels to stand up. Push your hips forwards at the top, then lower.'),
 ('Leg Press', 45, 5, 8, 10, 1, 'Sit in the machine positioned correctly according to the instructions. Place your feet lower and closer together to work your quads more, or higher and wider to hit your hamstrings and glutes more directly. Bend your knees to bring them towards your chest, then press back to the start.'),
 ('Dumbell Lunge', 30, 3, 8, 5, 1, ' Stand tall, holding a dumbbell in each hand. With your chest up and core braced, take a big step forwards with your left leg and lunge down until both knees are bent at 90°. Push off your front foot to return to the start, then repeat with your right leg. Alternate your leading leg with each rep.'),
 ('Front Squat', 60, 3, 10, 8, 1, 'Set a barbell on a power rack at about shoulder height. Grab the power with an overhand grip at shoulder width and raise your elbows until your upper arms are parallel to the floor. Take the bar out of the rack and let it rest on your fingertips. Your elbows should be all the way up throughout the movement. Step back and set your feet at shoulder width with toes turned out slightly. Squat as low as you can without losing the arch in your lower back.'),
 ('Walking Lunge', 20, 3, 12, 10, 1, 'Stand with your feet hip width, holding a dumbbell in each hand. Step forward with one leg and lower your body until your rear knee nearly touches the floor and your front thigh is parallel to the floor. Step forward with your rear leg to perform the next rep.'),
 ('Reverse Lunge', 30, 3, 10, 5, 1, 'Stand with the dumbbells still in your hands and step back with your right foot. Lower your body until your front thigh is parallel to the floor and your rear knee nearly touches the floor. Keep your torso upright. Step forward to return to the starting position. Complete all reps on one leg, then switch legs. That’s one set.'),
 ('Kettle Bell Swing', 30, 3, 8, 5, 1, 'Stand with feet hip-width apart and the kettlebell on the floor. Grasp the weight with both hands (palms facing you) and, keeping your lower back flat, extend your hips to raise it off the floor. From there, take a deep breath and bend your hips back, allowing the weight to swing back between your legs. Explosively extend your hips and exhale—allowing the momentum to swing the weight up to shoulder level. Control the descent, but use the momentum to begin the next rep.'),
 ('Jump Squat', 0, 4, 8, 8, 1, 'Stand with feet shoulder-width apart and squat down until your thighs are about parallel to the floor but no deeper. Jump as high as you can. Land with soft knees and begin the next rep.'),
 ('Kneeling Hip Flexor Stretch', 0, 3, 15, 5, 1, 'Kneel down in a lunge position with your right leg in front, and rest your back knee on a towel or mat, if available. Extend your left hand above your head and let your right hand hang at your side. Contract your left glute and push your hips forward until you feel a stretch in the front of your hip. Hold for 30 seconds.'),
 
 /*data for 4/8  */
 
 ('Back Squat', 65, 3, 6, 6, 1, 'Grip the bar with the hands wider than shoulder-width apart. Lift the chest up and squeeze the shoulder blades together to keep the straight back throughout the entire movement. Stand up to bring the bar off the rack and step backwards, then place the feet so that they are a little wider than shoulder-width apart. Sit back into hips and keep the back straight and the chest up, squatting down so the hips are below the knees. From the bottom of the squat, press feet into the ground and push hips forward to return to the top of the standing position.'),
 ('Front Squat', 30, 4, 5, 10, 1, ' Stand with your feet slightly wider than hip-width, facing outward or turned slightly outwards while holding a dumbbell in each hand by your sides, with palms facing inwards.Continue to lower yourself until your thighs are parallel or almost parallel with the floor, or until your heels begin to lift off the floor, or until your torso begins to round or flex forward. Push back up to starting position.'),
 ('Hip Hinge', 65, 3, 10, 5, 1, 'While standing, position your feet shoulder-width apart, side-by-side, with your toes pointed forward or slightly outward. Take a light bar and place it behind your head grasping the end with one hand above your head and the other end with your opposite hand in the small of your back. Push your hips backwards towards the wall behind you and hinge forward at the hips. Gently inhale and return to upright positun contracting your glutes.'),
 ('Leg Crossover Stretch', 0, 1, 5, 5, 1, 'Lie flat on your back on the floor / mat in a bent-knee position. Gently exhale and slowly press the knee of the crossed leg away from your body, continue pushing your knee away from you until you reach the point of tension, avoid bouncing or pushing to the point of pain. Hold this position for 15 – 30 seconds then relax and return to your starting position.  Perform 2 – 4 repetitions then repeat to the opposite side.'),
 
 
 SELECT * 
 FROM exercise
 WHERE body_target_id = 5;
 
 INSERT INTO trainers_exercises(exercise_id, trainer_id)
 VALUES(41, 1),(42, 1),(43, 1),(44,1), (4, 1), 
        (5, 1), (7, 1), (9, 1), (12, 1), (15, 1),
        (19, 1), (20, 1), (21, 1), (34, 1), (39, 1),
        (45, 1), (48, 1), (47, 1), (57, 1);
 